name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: macos-11

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Bundle install
      run: bundle update --bundler && bundle install
    - name: Run tests
      run: DEVELOPER_DIR="/Applications/Xcode_13.1.app/Contents/Developer" ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no github.com && xcodebuild -resolvePackageDependencies && bundle exec fastlane tests
